//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLevel
    {
        public AccessLevel()
        {
            this.Admins = new HashSet<Admin>();
        }
    
        public int accessLevel1 { get; set; }
        public string describeLevel { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
    }
}
