//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int idAdmin { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Fulname { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> lastLoginDate { get; set; }
        public Nullable<int> accessLevel { get; set; }
    
        public virtual AccessLevel AccessLevel1 { get; set; }
    }
}
