//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisment
    {
        public int idAd { get; set; }
        public string nameAd { get; set; }
        public string imgAd { get; set; }
        public string linkAd { get; set; }
    }
}
