//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMob.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameStoreDBEntities : DbContext
    {
        public GameStoreDBEntities()
            : base("name=GameStoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessLevel> AccessLevels { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Advertisment> Advertisments { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<nhaSanXuat> nhaSanXuats { get; set; }
        public virtual DbSet<SeriesGame> SeriesGames { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
