//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Genres = new HashSet<Genre>();
        }
    
        public int idGame { get; set; }
        public string nameGame { get; set; }
        public Nullable<int> idSeries { get; set; }
        public Nullable<int> idNhaSX { get; set; }
        public string describeGame { get; set; }
        public string linkDownload { get; set; }
        public string poster { get; set; }
        public Nullable<int> namSX { get; set; }
        public Nullable<int> luotDownLoad { get; set; }
        public Nullable<double> pointOfCritic { get; set; }
    
        public virtual nhaSanXuat nhaSanXuat { get; set; }
        public virtual SeriesGame SeriesGame { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
    }
}
