//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameMob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Games = new HashSet<Game>();
        }
    
        public int idGenre { get; set; }
        public string nameGenre { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
    }
}
